### ISSUE TITLE
Implement bullet point styling in HTML / CSS

### ISSUE THREAD

**Issue by pgundlach** [speedata/publisher#286]
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    ul {
      list-style: none;
      padding-left: 0;
    }
    ul li::before {
      content: "\2022";
      color: red;
      font-weight: bold;
      display: inline-block;
      width: 1em;
      margin-left: 0em;
    }
  </style>
</head>
<body>
  <ul>
    <li>hello</li>
    <li>world</li>
  </ul>
</body>

</html>
```

This should be the output:

<img width="187" alt="listyle" src="https://user-images.githubusercontent.com/209434/102189881-98e4c980-3eb7-11eb-91d8-5aec8387a68e.png">

**Comment by pgundlach** [comment]
```xml
<Layout xmlns="urn:speedata.de:2009/publisher/en"
	xmlns:sd="urn:speedata:2009/publisher/functions/en">
	<Stylesheet filename="mystyle.css"/>
	<Record element="data">
		<PlaceObject>
			<Textblock>
				<Paragraph>
					<Value select="."></Value>
				</Paragraph>
			</Textblock>
		</PlaceObject>
	</Record>
</Layout>
```

css:

```css
ul {
  list-style: none;
  padding-left: 1em;
}
ul li::before {
  content: "\2022";
  color: red;
  font-weight: bold;
  display: inline-block;
  width: 1em;
  margin-left: -1em;
}
```

data:

```xml
<data>
    <p>text</p>
    <ul>
        <li>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.</li>
        <li>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.</li>
    </ul>
    <p>text</p>
</data>
```

is a suitable input.
